### ISSUE TITLE
期望提供一份中文版本的d.ts文件

### ISSUE THREAD

**Issue by nxboo** [AgoraIO/rtc-web-archive#13]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/agora-rtc-sdk/index.d.ts

**Comment by disoul** [comment]
.d.ts 只能支持一个文件，英文是出于通用化的考虑

**Comment by nxboo** [comment]
要以另起一个名字吧？多加一份。比如：agora-rtc-sdk-zh
声网的服务还是国内用户多。对于英文不好的人，这份.d.ts文件失去了文档的功能，还是要对着官网文档开发，很不方便
