### ISSUE TITLE
Can we use this plugin in Electron ?

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/rtc-web-archive#23]
I want to use this plugin in Electron.
But I couldn't use the screen sharing function.

Thank you!

**Comment by digitallysavvy** [comment]
For Electron please use the [Agora Electron SDK](https://github.com/AgoraIO/Electron-SDK)

**Comment by yukitaka13-1110** [comment]
@digitallysavvy Thank you for your answer.

Isn't it recommended to use this plugin not electron-sdk?
