### ISSUE TITLE
`ERROR: getUserMedia NOT_SUPPORTED` iOS

### ISSUE THREAD

**Issue by dtkcs01** [AgoraIO/rtc-web-archive#31]
Hi, I am trying to make a live streaming application using `agora-rtc-sdk-ng` and have set up a basic codebase that works just fine on android/computers. But when try to join as a host from iPhones, I usually get this error `getUserMedia NOT_SUPPORTED`. Can you please help me out. I was unable to find anything online in this regards

**Comment by plutoless** [comment]
do you use safari directly or use webview? webrtc on safari do have some limitations

**Comment by plutoless** [comment]
do you use safari directly or use webview? webrtc on safari do have some limitations

**Comment by dtkcs01** [comment]
This issue also comes often when using chrome/firefox on iPhones.

**Comment by plutoless** [comment]
@dtkcs01 that's limitation on iphone webview. webrtc device capabilities are not supported in iphone webview.

**Comment by dtkcs01** [comment]
So is there any kind of workaround such limitations to ensure a smoother experience for users on the iPhone using chrome/firefox?

**Comment by plutoless** [comment]
you have to use native. there's no workaround for iphone webview

**Comment by dtkcs01** [comment]
Thank you... closing this as clear...
