### ISSUE TITLE
"agora-rtc-sdk" or "agora-rtc-sdk-ng"?

### ISSUE THREAD

**Issue by Abror1997** [AgoraIO/rtc-web-archive#36]
I have the following questions:
 - Why there are 2 packages: `agora-rtc-sdk` and `agora-rtc-sdk-ng`?
 - Which one should I use?

_PS: I see that `agora-rtc-sdk-ng` uses 4.x.x version and `agora-rtc-sdk` uses 3.x.x._

**Comment by Naeemo** [comment]
I have used both under different circumstances.
The `ng` one is written with TS, actively maintained right now and recommended. Seems new features will only be added to this one.

**Comment by Abror1997** [comment]
@Naeemo Thanks for the information. I will use `ng` then.
