### ISSUE TITLE
agora-rtc-sdk new version (3.6.4) audio doesn't work

### ISSUE THREAD

**Issue by PedroHenrike20** [AgoraIO/rtc-web-archive#38]
Hello community, I made a video call system based on this repository https://github.com/AgoraIO-Community/OpenAgoraWeb-React and according to the last chrome update every call made, most of the time one of the users appeared with the screen all black. I received a recent email from Agora.io asking to update the package, but every time I start my call on this new version one of the users loses the audio system. Can someone help me please? Thanks until then.. NOTE: until version 2.9.0 agora-rtc-sdk, the audio worked normally.

**Comment by plutoless** [comment]
could you pls provide the log files for us to investigate?

**Comment by PedroHenrike20** [comment]
where can i find these log files?

**Comment by PedroHenrike20** [comment]
[addvalora.com.br-1631735730119.log](https://github.com/AgoraIO/rtc-web-archive/files/7172896/addvalora.com.br-1631735730119.log)
