### ISSUE TITLE
使用switchDevice 的时候报错

### ISSUE THREAD

**Issue by Xiaofuziod** [AgoraIO/rtc-web-archive#4]
agora-rtc-sdk版本2.8.0
错误：
![image](https://user-images.githubusercontent.com/25679654/62418573-ba685b00-b69e-11e9-8552-a8fc91f1805a.png)

**Comment by plutoless** [comment]
浏览器版本？移动端吗

**Comment by Xiaofuziod** [comment]
是electron项目，chrome内核版本是73.我换了一种创建createStream方式
![image](https://user-images.githubusercontent.com/25679654/62418863-4336c500-b6a6-11e9-9de6-2f4c461da35f.png)
 出现了新的报错。
![image](https://user-images.githubusercontent.com/25679654/62418858-1bdff800-b6a6-11e9-8bf5-a95de680a0a7.png)
这块是需要在调用switchDevice之前调用别的什么暂停之类的方法吗？

**Comment by Xiaofuziod** [comment]
忘了文档中说明了使用自采集属性（audioSource 和 videoSource）创建的流无法使用这个方法  但是我使用
![image](https://user-images.githubusercontent.com/25679654/62418993-2059e000-b6a9-11e9-9189-d6110c9fc5d3.png) createStream之后再调用
switchDevice 会出现
![image](https://user-images.githubusercontent.com/25679654/62419004-6020c780-b6a9-11e9-8fce-135219f20718.png)的报错。正确的打开方式是什么呢？

**Comment by plutoless** [comment]
switchDevice怎么调的？

**Comment by Xiaofuziod** [comment]
![image](https://user-images.githubusercontent.com/25679654/62419052-5ba8de80-b6aa-11e9-935b-5920249b1a6a.png)
![image](https://user-images.githubusercontent.com/25679654/62419053-619ebf80-b6aa-11e9-8bde-048d8b81c9ae.png)

**Comment by plutoless** [comment]
看上面的错，要不就是你的localStream没初始化完成，要么就是你指定的deviceId不存在

**Comment by Xiaofuziod** [comment]
localStream应该初始化完成了 因为我将本地流推上去 在别的地方拉流是正常播放的然后才调用的switchDevice。而deviceId我使用AgoraRTC.getDevices获取的结果。

**Comment by plutoless** [comment]
有最小复现demo吗? 我跑一下看看

**Comment by Xiaofuziod** [comment]
好的 稍后我写一个demo 下午麻烦您看一下。

**Comment by Xiaofuziod** [comment]
在我重新安装了依赖之后好了。 可以正常使用了。谢谢大佬。
