### ISSUE TITLE
Cannot find v4.x on NPM!

### ISSUE THREAD

**Issue by deevannaveed** [AgoraIO/rtc-web-archive#40]
I am wondering why would you not publish v4.x on NPM!

**Comment by plutoless** [comment]
@deevannaveed our 4.x SDK evolves to be this https://www.npmjs.com/package/agora-rtc-sdk-ng
note the api could differ from legacy 3.x SDK versions. Enjoy.

**Comment by deevannaveed** [comment]
Thanks
