### ISSUE TITLE
Calling getDisplayMedia vastly reduces latency for screen sharing.

### ISSUE THREAD

**Issue by JamieCorkhill** [AgoraIO/rtc-web-archive#7]
Hello.

I'm attempting to use this SDK for the purposes of screen sharing. As per the docs, I create the stream as follows:

```javascript
AgoraRTC.createStream({
    streamID: 'uid',
    screen: true,
    audio: false,
    video: false
});
```
The issue here is that there is an abhorrent amount of latency and packet loss for the viewers of the screen-sharing stream.

Interestingly, if I call `getDisplayMedia` on `navigator.mediaDevices`, which you'd imagine would have no effect, the stream becomes a lot more clear:

```javascript
navigator.mediaDevices.getDisplayMedia();

AgoraRTC.createStream({
    streamID: 'uid',
    screen: true,
    audio: false,
    video: false
});
```
When I do this, it causes the pop up on Chrome to appear twice (one from my call to `getDisplayMedia` and one from `screen: true`), but it ends up leading to having a screen-sharing stream that's a lot smoother and sharper than not calling it if the user chooses the same option twice.

I'm completely puzzled here because I'm not even `await`ing the resolution of the promise to the `getDisplayMedia` call, yet this does cause vastly reduced latency. The only thing I can imagine is that doing this "initializes" the media devices/screen-sharing process in some manner.

This is in reference to my support ticket here: https://agora-ticket.agora.io/issue/0fd30275-2740-4255-9d9d-62b572151bed

Any help would be much appreciated, for this is a very important component to my service and a deciding factor on whether I proceed with an Agora integration.

Thanks for your time.

**Comment by JamieCorkhill** [comment]
Of course, that URL requires authentication. The ticket number is: CUS-3643

**Comment by JamieCorkhill** [comment]
It turns out I didn't notice that you expose a `setScreenProfile()` method. I fixed my FPS issue as such. Closing for resolution.

**Comment by plutoless** [comment]
ok good to know it's fixed :)
