### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by JamieCorkhill** [AgoraIO/rtc-web-archive#8]
Hello.

I'm attempting to utilize this SDK with TypeScript and React. I'm coming across an issue wherein the `AgoraRTC.Stream` interface is not at all compatible to the `MediaStream` interface, thus I can't set the `srcObject` without casting to `unknown` and then to `MediaStream`, as there's no overlap between the two. Are there any solutions to this?

I'm aware that you have another version of this library that supports TypeScript explicitly with Promises, but I'm wary of using it since I don't it may be unstable for production and there are certain features that are currently a work in progress (like video profiles).

Thank you.

**Comment by JamieCorkhill** [comment]
It turns out you're missing a `stream` property on the `AgoraRTC.Stream` interface as per your documentation. I'd be happy to close this and open it downstream on Definitely Typed if you wish.

**Comment by plutoless** [comment]
thank you for your insights on this. i'm raising this to web sdk team to take a look.

**Comment by ysclyy** [comment]
@JamieCorkhill  We don't hope people use `stream` property on the `AgoraRTC.Stream`, if you need to set the `srcObject`,   @ts-ignore may be work.

We encourage everyone use new SDK(what you call "another version of this library"), we do a lot of  improvement and use more test case to make it easy to use and stable （https://github.com/AgoraIO-Community/AgoraWebSDK-NG）

**Comment by JamieCorkhill** [comment]
Thanks very much @ysclyy. I'd like to use that library, but it looks like you don't yet support video or screen profiles yet, which is a feature I very much need, otherwise screen sharing is stuck at 5 FPS (at least, it is in this library - I'll check tonight it that's the case in the new one). Either way, I do very much want to adopt your Promise-style lib so I can move away from callback hell. I was just worried that the new lib may not be suitable for production since you're still in beta.

**Comment by ysclyy** [comment]
@JamieCorkhill The NG SDK have the features what this SDK have, video or screen profiles  is already support, but English doc still in progress, it may be finish this week.
NG SDK reference:
https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/cameravideotrackinitconfig.html#encoderconfig
https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/globals.html#videoencoderconfigurationpreset

**Comment by JamieCorkhill** [comment]
Thanks very much @ysclyy. I'm trying it out now. I appreciate your time.
