### ISSUE TITLE
[bug] onTokenPrivilegeWillExipire is triggered only once time

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/rtc-web-archive#9]
I use appCertificate in my project.
After implement server side (token expired time -> 60s), I tried to retrieve token and `renewToken`.
`onTokenPrivilegeWillExipire` triggered and I could success call `renewToken` with token that first time I generate, and continue to stream video.
But second `onTokenPrivilegeWillExipire` event has not been fired.
However, video streaming has continued all the time.

My server side code is the following.

```ts
function retrieveRtcToken(
  appId: string,
  appCertificate: string,
  uid: number,
  channelName: string
): string {
  const role = RtcRole.PUBLISHER;
  const expirationTimeInSeconds = 60;
  const currentTimestamp = Math.floor(Date.now() / 1000);
  const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds;
  return RtcTokenBuilder.buildTokenWithUid(
    appId,
    appCertificate,
    channelName,
    uid,
    role,
    privilegeExpiredTs
  );
}
```

**Comment by yukitaka13-1110** [comment]
https://github.com/AgoraIO-Community/Agora-RTM-Nodejs/issues/15

**Comment by plutoless** [comment]
can you try putting the expire time a little bit longer? say 5 mins

**Comment by peicodes** [comment]
I'm having this issue as well. I set mine to 60 seconds.

As soon as you make a change to your client (like ending your stream), it will throw a token expired error without any additional `onTokenPrivilegeWillExpire` or `onTokenPrivilegeDidExpire` events.

**Comment by plutoless** [comment]
we confirmed this is current behavior and we are checking when SDK team can fix it.

**Comment by yukitaka13-1110** [comment]
@plutoless 
Any updates from SDK team ?

**Comment by plutoless** [comment]
@yukitaka13-1110 we have an internal jira following on this issue. i think they are still working on the fix.

**Comment by peicodes** [comment]
@plutoless Could you share an update on that jira ticket?

**Comment by plutoless** [comment]
@peicodes i was told this issue has been fixed. could you pls help double check?

**Comment by peicodes** [comment]
@plutoless I just re-implemented a 60 second expiry, and it's working. Thanks for the fix!
